"""Contenuti del Diario di Baruch.

Testi di Caterina Santambrogio provenienti da illustraremondi.it, organizzati nelle
cinque sezioni del diario. Per aggiungere una pagina: nuova voce in ARTICOLI
(le immagini vanno in img/articoli/<nome>-720.webp e <nome>-1400.webp), poi python _build.py

Blocchi di un articolo:
  ("p", testo)            paragrafo
  ("h", testo)            titoletto
  ("q", testo)            citazione su pennellata
  ("img", nome, alt)      immagine; più immagini consecutive diventano una griglia
"""

SEZIONI = [
    {
        "slug": "le-avventure-di-baruch",
        "titolo": "Le avventure di Baruch",
        "disegno": "avventure", "w": 860, "h": 829,
        "alt": "Uno zaino dipinto con i colori di un prato",
        "classe": "d-avv",
        "intro": [
            "L’avventura è un modo di vivere, non un traguardo lontano. Per me ogni uscita è una spedizione: che sia tra le sale di un museo, nel silenzio di una chiesa o lungo un sentiero dietro casa, parto sempre per scoprire qualcosa che prima non vedevo.",
            "Qui raccolgo i miei appunti visivi: schizzi rapidi per fermare quel senso di viaggio che provo anche a pochi chilometri da dove abito.",
        ],
    },
    {
        "slug": "come-fiori-selvatici",
        "titolo": "Come fiori selvatici",
        "disegno": "fiori-selvatici", "w": 900, "h": 1498,
        "alt": "Un ramo di margherite rosa disegnato a matita e acquerello",
        "classe": "d-fiori",
        "intro": [
            "Selvatico è ciò che cresce senza chiedere permesso. Per me la natura è il luogo del riparo e della bussola: quando mi perdo, torno ad osservare i ritmi lenti della terra.",
            "E disegno per ritrovare frammenti di quel mondo rigenerante, estratti di piante e vita animale che segnano la strada per ritrovare sé stessi.",
        ],
    },
    {
        "slug": "costruire-con-baruch",
        "titolo": "Costruire con Baruch",
        "disegno": "costruire", "w": 900, "h": 819,
        "alt": "Due mani disegnano con una matita su un foglio colorato",
        "classe": "d-cost",
        "intro": [
            "Progettare, sporcarsi, sbagliare, finire. I laboratori sono il luogo dove la tecnica incontra il gioco, per ogni età. Qui trovi i miei workshop e le novità sui prossimi incontri.",
            "Non serve essere artisti per partecipare: serve la curiosità di smontare il mondo e ricostruirlo con i propri colori.",
        ],
    },
    {
        "slug": "i-mondi-disegnati-di-baruch",
        "titolo": "I mondi disegnati di Baruch",
        "disegno": "mondi-disegnati", "w": 900, "h": 543,
        "alt": "Una casetta fatta di foglie d’autunno con la sua ombra",
        "classe": "d-mondi",
        "intro": [
            "In questa sezione raccolgo i lavori realizzati su commissione: progetti nati dall’incontro con le esigenze dei clienti e trasformati in mondi visivi compiuti.",
            "Partendo dall’idea, la tecnica si mette al servizio della narrazione per dare forma e colore a storie e progetti.",
        ],
        # opere: (immagine, titolo, tecnica, alt); il dettaglio di ciascuna è in OPERE
        "opere": [
            ("06-prove-di-volo", "Calendario illustrato “Prove di volo”", "Tecnica mista: gouache e digitale", "Un campo di papaveri rossi sotto un grande cielo arancione"),
            ("ritratto-07", "Calendario “Che effetto ti fa?”", "Tecnica mista: acrilico e pastello su carta", "Ritratti di volti sorridenti tra fiori, foglie e ritagli"),
            ("teatro-sotto-gli-alberi", "Teatro sotto gli alberi", "Tecnica mista: gouache e digitale", "Bambini e animali giocano tra alberi con le gambe, in un prato fiorito"),
            ("yan-e-lorso", "Yan e l’Orso", "Tecnica mista: acrilico e digitale", "Un bambino dorme sulla schiena di un grande orso"),
            ("calendario", "Calendario “Vuoi guarire?”", "Tecnica mista: gouache e digitale", "Una donna dai capelli rossi suona un liuto"),
        ],
    },
    {
        "slug": "le-cose-magiche-di-baruch",
        "titolo": "Le cose magiche di Baruch",
        "disegno": "cose-magiche", "w": 900, "h": 604,
        "alt": "Baruch cavalca un cavallino di legno",
        "classe": "d-magiche",
        "intro": [
            "Uso il legno, l’argilla e il segno per trasformare l’uso comune in un viaggio visivo. Qui non ci sono serie uguali, ma oggetti singoli, che siano tazze illustrate, teiere o elementi d’arredo, che funzionano come bussole per l’immaginario.",
            "Frammenti di un mondo leggero che nascono per essere tenuti tra le mani e per traslocare una piccola storia nello spazio che abitiamo.",
        ],
        # oggetti: (percorso immagine 720, percorso 1400/1600, titolo, alt, w, h)
        "gruppi": [
            ("Ceramica", [
                ("img/articoli/ceramica-720.webp", "img/articoli/ceramica-1400.webp", "Teiera in ceramica con tulipani", 720, 720),
                ("img/galleria/img-6431-720.webp", "img/galleria/img-6431-1600.webp", "Teiera in ceramica con un uccellino sul coperchio", 720, 821),
                ("img/galleria/15-ciondoli-720.webp", "img/galleria/15-ciondoli-1600.webp", "Ciondoli in ceramica dipinti con volti e foglie blu", 720, 660),
            ]),
            ("Decorazione di mobili", [
                ("img/articoli/decorazione-di-mobili-720.webp", "img/articoli/decorazione-di-mobili-1400.webp", "Un armadio dipinto con una figura tra gli alberi", 720, 720),
                ("img/galleria/19-sedia-720.webp", "img/galleria/19-sedia-1600.webp", "Una sedia di legno decorata con case e alberi", 720, 1018),
            ]),
        ],
    },
]

# Le opere su commissione della sezione "I mondi disegnati": ognuna ha la sua pagina.
# Le tavole stanno in img/opere/<nome>-720.webp e -1400.webp.
OPERE = [
    {
        "slug": "prove-di-volo",
        "cover": "06-prove-di-volo",
        "titolo": "Calendario illustrato “Prove di volo”",
        "breve": "Prove di volo",
        "categoria": "Illustrazioni",
        "con": "Con l’associazione Bereshit",
        "tecnica": "Tecnica mista: gouache e digitale",
        "testi": [
            "Il calendario illustrato “Prove di volo” nasce dal bisogno profondo di ritrovare una spinta interiore e dare nuovo colore alle relazioni, agli incontri e all’ambiente che ci circonda.",
            "In queste illustrazioni, realizzate in collaborazione con l’associazione Bereshit, non ci sono persone, volti o mani. Ci sono solo voli. Uccelli leggeri che decorano il cielo, respirano il tramonto, riflettono la notte e sollevano fiori.",
        ],
        "citazione": "Un invito poetico a piantare lo sguardo dritto nel cuore della natura, per ripartire dalla bellezza della creazione.",
        "tavole": [
            ("01-prove-di-volo", "Un uccello fatto di foglie gialle vola sopra una scala e una casetta rossa nella notte blu"),
            ("03-prove-di-volo", "Un uccello verde tra canne e fiori sotto un cielo blu"),
            ("04-prove-di-volo", "Due uccelli trasparenti tra erbe al tramonto"),
            ("05-prove-di-volo", "Un uccello rosso e giallo tra foglie colorate"),
            ("08-prove-di-volo", "Un uccellino solleva un grande prato di fiori rossi e arancioni"),
            ("09-prove-di-volo", "Uccelli verdi in volo su uno sfondo giallo"),
        ],
        "pdf": ("pdf/calendario-prove-di-volo.pdf", "Sfoglia il calendario 2023", "PDF, 11 MB"),
    },
    {
        "slug": "che-effetto-ti-fa",
        "cover": "ritratto-07",
        "titolo": "Calendario “Che effetto ti fa?”",
        "breve": "Che effetto ti fa?",
        "sottotitolo": "Un atlante di volti ed emozioni",
        "categoria": "Illustrazioni",
        "con": "Con l’associazione Bereshit",
        "tecnica": "Tecnica mista: acrilico e pastello su carta",
        "testi": [
            "Questo calendario illustrato, realizzato in collaborazione con l’associazione Bereshit, nasce come un piccolo viaggio illustrato tra le sfumature che ci attraversano ogni giorno.",
            "Attraverso i disegni ho voluto dare forma e colore alla nostra “preziosa instabilità”: uno sguardo, un volto, la paura o la leggerezza diventano tracce visive per accorgerci di ciò che proviamo e ritrovare un’eco di noi stessi mese dopo mese.",
        ],
        "citazione": "",
        "tavole": [
            ("ritratto-03", "Un ragazzo abbraccia il suo cane tra trifogli, con la parola fiducia"),
            ("ritratto-08", "Una donna con un foulard tra fiori, conchiglie e appunti"),
            ("ritratto-09", "Un uomo con la barba bianca tra foglie secche e il ritratto di un neonato"),
            ("ritratto-010", "Una madre stringe il suo bambino, con la scritta la tenerezza"),
            ("ritratto-011", "Un ragazzo urla divertito tra alchechengi e bacche"),
            ("ritratto-012", "Una ragazza e un uomo con il naso rosso da clown, con la scritta che stupore"),
        ],
        "pdf": None,
    },
    {
        "slug": "teatro-sotto-gli-alberi",
        "cover": "teatro-sotto-gli-alberi",
        "titolo": "Teatro sotto gli alberi",
        "breve": "Teatro sotto gli alberi",
        "sottotitolo": "Un progetto di teatro e bosco",
        "categoria": "Rassegne teatrali",
        "con": "Per Molino Rosenkranz",
        "tecnica": "Tecnica mista: gouache e digitale",
        "testi": [
            "Per la rassegna estiva “A teatro sotto gli alberi” di Molino Rosenkranz, ho giocato con l’illusione delle ombre: braccia e mani si tendono verso l’alto per trasformarsi nei tronchi e nei rami di un bosco surreale.",
        ],
        "citazione": "Un manifesto visivo dove la natura e la finzione teatrale si fondono in un unico segno, invitando il pubblico a entrare in un esterno magico.",
        "tavole": [
            ("teatro-sotto-gli-alberi-04", "Il manifesto A teatro sotto gli alberi con una mano verde che diventa albero"),
            ("teatro-sotto-gli-alberi-02", "Un albero con le gambe accanto a una tenda rossa in un prato fiorito"),
            ("teatro-sotto-gli-alberi-03", "Bambini che leggono sugli alberi e un uccello colorato nel prato"),
            ("teatro-sotto-gli-alberi-01", "Striscione orizzontale con alberi, bambini e fiori"),
        ],
        "pdf": None,
    },
    {
        "slug": "yan-e-l-orso",
        "cover": "yan-e-lorso",
        "titolo": "Yan e l’Orso",
        "breve": "Yan e l’Orso",
        "sottotitolo": "Le pareti di una yurta che si fanno pagina",
        "categoria": "Storie illustrate",
        "con": "Per Molino Rosenkranz",
        "tecnica": "Tecnica mista: acrilico e digitale",
        "testi": [
            "Per Molino Rosenkranz ho disegnato una storia stampata su stoffa, pensata per avvolgere i piccoli spettatori all’interno di uno spazio circolare e protetto.",
        ],
        "citazione": "Un allestimento dove l’illustrazione diventa scenografia e la stoffa si fa tenda tesa verso l’immaginario, per dare corpo ad una narrazione teatrale intima e pulsante.",
        "tavole": [
            ("yan-e-lorso-01", "Un’orsa abbraccia una madre e il suo bambino vestiti con abiti del nord"),
            ("yan-e-lorso-02", "Un bambino con abiti tradizionali cammina nella neve"),
            ("yan-e-lorso-03", "Una renna tra betulle, dipinta sulla stoffa"),
            ("yan-e-lorso-04", "Lo sviluppo circolare della tenda con tutte le scene della storia"),
            ("yan-e-lorso-05", "La tenda montata in un cortile accanto a un orso che saluta"),
        ],
        "pdf": None,
    },
    {
        "slug": "vuoi-guarire",
        "cover": "calendario",
        "titolo": "Calendario “Vuoi guarire?”",
        "breve": "Vuoi guarire?",
        "sottotitolo": "Dodici mesi per raccontare il ritorno alla vita",
        "categoria": "Illustrazioni",
        "con": "Con l’associazione Bereshit",
        "tecnica": "Tecnica mista: gouache e digitale",
        "testi": [
            "In questa collaborazione con l’associazione Bereshit, le parole del Vangelo incontrano il segno grafico per esplorare il concetto di guarigione.",
            "Le tavole giocano su una palette essenziale in cui il rosso e il blu si cercano, unite a una composizione serrata che stringe l’inquadratura sui dettagli essenziali.",
        ],
        "citazione": "Eliminando il superfluo, ogni mese diventa uno spazio calmo dove riflettere sul senso del testo.",
        "tavole": [
            ("calendario-01", "Una donna dai capelli rossi dorme sotto una colomba bianca"),
            ("calendario-02", "Un angelo e una donna velata con una colomba blu"),
            ("calendario-03", "Tre donne suonano e cantano con strumenti antichi"),
            ("calendario-04", "Due uomini si abbracciano, uno vestito di rosso"),
            ("calendario-05", "Una tavola con pane e vino tra figure in abiti chiari"),
        ],
        "pdf": ("pdf/calendario-vuoi-guarire.pdf", "Sfoglia il calendario 2021", "PDF, 17 MB"),
    },
]

ARTICOLI = [
    {
        "slug": "solidi-e-chiaroscuro",
        "sezione": "costruire-con-baruch",
        "data": "2026-07-12", "data_it": "12 luglio 2026",
        "titolo": "Solidi e chiaroscuro",
        "sottotitolo": "Disegno dal vero",
        "estratto": "Un disegno dal vero si trasforma in un’avventura surreale se si decide di non fermarsi alla superficie delle cose.",
        "cover": ("solidi-e-chiaroscuro-01", "Due solidi di legno disegnati: una torre con una scala e un cubo con una sfera"),
        "blocchi": [
            ("p", "Un semplice esercizio di disegno dal vero può trasformarsi in un’avventura surreale quando si decide di non fermarsi alla superficie delle cose. Tutto è iniziato sul tavolo da lavoro, riprendendo in mano le basi: la matita, lo studio dei solidi geometrici, la ricerca rigorosa del chiaroscuro e della consistenza del legno."),
            ("p", "Un esercizio necessario per allenare l’occhio e la mano, ma che rischiava di scivolare nella monotonia. Così, ho deciso di infrangere le regole dell’accademia. È bastato un leggero velo di colore, l’intaglio di una piccola porta segreta nel cuore di un cubo e una scala tesa verso l’alto per cambiare la natura di quelle forme."),
            ("img", "solidi-e-chiaroscuro-03", "Solidi colorati di azzurro e lilla con una piccola porta e una bandiera"),
            ("img", "solidi-e-chiaroscuro-04", "Studio a matita di cubi, cilindri e sfere in chiaroscuro"),
            ("q", "Quei blocchi di legno non erano più geometrie inanimate, ma architetture silenziose di un mondo sconosciuto tutto da esplorare."),
            ("p", "Immergersi in questo spazio nuovo significa riscoprire che l’avventura non richiede grandi viaggi, ma solo la voglia di guardare oltre il confine del foglio…"),
            ("img", "solidi-e-chiaroscuro-05", "Una torre di legno con una scala appoggiata e un cubo sormontato da una sfera"),
        ],
    },
    {
        "slug": "vegetazione-selvaggia",
        "sezione": "costruire-con-baruch",
        "data": "2026-05-08", "data_it": "8 maggio 2026",
        "titolo": "Vegetazione selvaggia",
        "sottotitolo": "Tra masse verdi e la strada di casa",
        "estratto": "La pittura espressiva di masse verdi e boschi attraverso un segno istintivo.",
        "cover": ("vegetazione-selvaggia-06", "Un volto sorridente spunta tra grandi foglie verdi dipinte"),
        "blocchi": [
            ("img", "vegetazione-selvaggia-01", "Un bosco fitto dipinto con pennellate verdi e nervose"),
            ("q", "Invenzioni disegnate e sperimentazioni del giorno: la pittura espressiva di masse verdi e boschi attraverso un segno istintivo."),
            ("p", "Oggi la mia ricerca si sposta verso una gestualità più nervosa, quasi agitata. Non cerco la precisione botanica, ma l’energia del bosco: dipingo di getto grandi masse verdi che si sovrappongono, usando il colore come se fosse un respiro affannato tra gli alberi."),
            ("p", "In mezzo a questa vegetazione intricata appare una figura. È un corpo disegnato con segni densi, graffiati, quasi fosse un taccuino vivente. Sembra smarrita, impegnata a cercare la strada di casa tra i rami e le ombre."),
            ("p", "In questa sperimentazione artistica, il tratto non descrive solo un luogo, ma uno stato d’animo: quel momento in cui il paesaggio interiore e quello reale si fondono nel tentativo di ritrovarsi."),
            ("img", "vegetazione-selvaggia-02", "Alberi dipinti lungo un sentiero chiaro"),
            ("img", "vegetazione-selvaggia-03", "Una figura nascosta tra i tronchi di un bosco scuro"),
            ("img", "vegetazione-selvaggia-04", "Chiome di alberi dipinte a macchie di verde"),
            ("img", "vegetazione-selvaggia-05", "Un bosco verde con un sentiero in primo piano"),
        ],
    },
    {
        "slug": "prugno-selvatico",
        "sezione": "come-fiori-selvatici",
        "data": "2026-05-06", "data_it": "6 maggio 2026",
        "titolo": "Prugno selvatico",
        "sottotitolo": "Disegno naturalistico del prugno selvatico",
        "estratto": "Per questa nuova tappa del mio viaggio di disegno naturalistico, oggi scelgo il bianco delicato del prugno selvatico.",
        "cover": ("prugno-selvatico-04", "Rami e fiori di prugno selvatico disegnati a inchiostro rosso"),
        "blocchi": [
            ("img", "prugno-selvatico-01", "Bozzetti liberi di fiori ad acquerello con appunti scritti a mano"),
            ("p", "Per questa nuova tappa del mio viaggio di disegno naturalistico, oggi scelgo il bianco delicato del prugno selvatico. Inizio sempre sciogliendo la mano con schizzi liberi sul taccuino per capire quale forma studiare."),
            ("img", "prugno-selvatico-02", "Pagina di taccuino con casette, fiori e la scritta Vivere fiorendo"),
            ("p", "Ma prima dei bozzetti c’è il desiderio: un qualcosa che mi piace e che spinge per farsi strada. Da qui nasce VIVERE FIORENDO, dalla necessità di ritrovare entusiasmo e energia nella quotidianità. È un progetto che trasforma lo studio botanico in una serie di illustrazioni accennate e possibili pattern."),
            ("p", "È un’idea che immagino già su nuovi oggetti, come queste prime bozze per delle shopper."),
            ("img", "prugno-selvatico-03", "Bozzetti di volti, fiori di prugno e una borsa decorata"),
            ("q", "Disegnare è anche dare al desiderio la forza di fiorire."),
        ],
    },
    {
        "slug": "il-respiro-del-tagliamento",
        "sezione": "le-avventure-di-baruch",
        "data": "2026-05-04", "data_it": "4 maggio 2026",
        "titolo": "Il respiro del Tagliamento",
        "sottotitolo": "Tra sassi, cuori e sfumature",
        "estratto": "Le rive del Tagliamento, nella zona di Gradisca di Spilimbergo, regalano sempre un ampio respiro.",
        "cover": ("fiume-tagliamento-01", "Il greto del fiume Tagliamento dipinto con sassi impilati"),
        "blocchi": [
            ("h", "Gita sulle rive del Tagliamento: collezionare pesi e leggerezza"),
            ("p", "Le rive del Tagliamento, nella zona di Gradisca di Spilimbergo, regalano sempre un ampio respiro. Qui il gioco preferito è la sfida a chi scova il sasso più particolare: cerchiamo pietre a forma di cuore, sassi lisci e piatti perfetti per rimbalzare sull’acqua, o frammenti decorati da righe precise e sfumature che brillano appena bagnate dal fiume."),
            ("img", "il-respiro-del-tagliamento-01", "Taccuino aperto con sassi disegnati e sassi veri"),
            ("img", "il-respiro-del-tagliamento-02", "Sassi raccolti accanto ai loro disegni su un tavolo di legno"),
            ("p", "Ho iniziato a collezionare i disegni di questi sassi, portando a casa la memoria di ogni luogo che visito. Ma per me i sassi non sono solo forme; sono anche legati all’idea del peso. In certi periodi difficili, è naturale associare la loro consistenza al peso della fatica che portiamo dentro."),
            ("p", "Eppure, ho scoperto che disegnarli è un po’ come osservare quella fatica da vicino: nel momento in cui la metto su carta, riesco a vederne le lievi sfumature e a trovarci persino qualcosa da apprezzare."),
            ("q", "Disegnare il peso, in fondo, è il mio modo per renderlo più leggero."),
            ("img", "il-respiro-del-tagliamento-03", "Collage di sassi disegnati e fotografie del fiume"),
            ("img", "il-respiro-del-tagliamento-04", "Una persona raccoglie sassi sulla riva e un ritratto con sassi in equilibrio sul naso"),
        ],
    },
    {
        "slug": "albero-di-giuda",
        "sezione": "come-fiori-selvatici",
        "data": "2026-05-02", "data_it": "2 maggio 2026",
        "titolo": "L’Albero di Giuda",
        "sottotitolo": "Il processo creativo di un pattern",
        "estratto": "Studio e disegno naturalistico dell’Albero di Giuda per la creazione di mondi illustrati.",
        "cover": ("albero-di-giuda-01", "Un ramo fiorito di Albero di Giuda, fiori rosa e il volto di una bambina"),
        "blocchi": [
            ("img", "fiore-di-giuda-01", "Fiori dell’Albero di Giuda che diventano uccellini, con appunti a mano"),
            ("p", "Il mio processo creativo parte spesso dall’osservazione della realtà: questa volta è il fiore dell’Albero di Giuda a catturare la mia attenzione. La sua forma irregolare, detta “papilionacea” perché ricorda una farfalla, mi ha suggerito un’idea magica: e se questi petali diventassero ali?"),
            ("img", "fiore-di-giuda-02", "Uccellini-fiore ripetuti in un pattern rosa e arancione"),
            ("p", "Così, lo studio botanico si trasforma in un uccellino buffo e leggero. Da un semplice bozzetto, la fantasia prende il sopravvento e il fiore diventa un disegno grafico pronto per trasformarsi in un pattern."),
            ("p", "Le potenzialità di questo viaggio sono infinite: partendo dalla natura, si possono creare mondi illustrati sempre diversi, scoprendo forme e storie che all’inizio non avrei mai immaginato."),
            ("q", "Quando l’immaginazione gioca, tutto diventa possibile."),
            ("img", "fiore-di-giuda", "Un muro dipinto a fiori in città accanto a un cervo in un prato"),
        ],
    },
    {
        "slug": "rosso-papavero",
        "sezione": "come-fiori-selvatici",
        "data": "2026-04-30", "data_it": "30 aprile 2026",
        "titolo": "Rosso papavero",
        "sottotitolo": "Viaggio nel mio taccuino di disegno naturalistico",
        "estratto": "Per questa nuova tappa nel mio taccuino di disegno naturalistico, oggi scelgo il rosso papavero.",
        "cover": ("rosso-papavero", "Papaveri rossi dipinti ad acquerello"),
        "blocchi": [
            ("p", "Per questa nuova tappa nel mio taccuino di disegno naturalistico, oggi scelgo il rosso papavero. Ho bisogno di questo colore che, come un’onda carica di vitalità, mi spinge con forza a credere che certe giornate hanno bisogno della bellezza delle piccole cose."),
            ("p", "Credo nella passione che sprigiona una fila di papaveri a bordo campo. Sembra disegnare un confine ordinato lungo la strada, ma poi lo sguardo scavalca quel limite, rapito da un intero prato rosso che gioca."),
            ("q", "Mentre cerco di catturare la fragilità dei petali che sembrano veline, nella mia memoria affiorano le corse in un campo di papaveri dove il colore si confonde con la gioia."),
            ("img", "rosso-papavero-01", "Studio di papaveri rossi con steli e boccioli"),
            ("img", "bozzetti-e-ricordi", "Una vecchia foto di un bambino tra i papaveri accanto a un bozzetto"),
            ("img", "bozzetti-e-ricordi-01", "Appunti scritti a mano e papaveri disegnati su un tessuto nero"),
            ("img", "bozzetti-e-ricordi-02", "Papaveri veri accanto ai disegni sul tavolo da lavoro"),
        ],
    },
    {
        "slug": "caraffa",
        "sezione": "costruire-con-baruch",
        "data": "2026-04-26", "data_it": "26 aprile 2026",
        "titolo": "Caraffa",
        "sottotitolo": "Le invenzioni disegnate iniziano da un dettaglio inaspettato",
        "estratto": "Tutto è partito da una caraffa, una di quelle ceramiche tipiche di Deruta, su cui è dipinto un piccolo omino medievale.",
        "cover": ("caraffa", "Un pupazzetto di carta a righe tra le foglie di un giardino"),
        "blocchi": [
            ("p", "Tutto è partito da una caraffa, una di quelle ceramiche tipiche di Deruta, su cui è dipinto un piccolo omino medievale. Mi ha catturato a tal punto che ho deciso di portarlo fuori dal piano della ceramica: ho realizzato un pupazzetto di carta ispirato a lui, ma con le articolazioni movibili."),
            ("p", "Grazie a un amico, quel personaggio ha preso vita in un video, iniziando a muoversi per pochi secondi, ma trascinando la mia immaginazione…"),
            ("img", "caraffa-02", "La caraffa di Deruta, il disegno dell’omino e il pupazzetto di carta"),
            ("p", "Ormai stregata dalla forma accogliente di quella caraffa, ho iniziato a disegnarla ancora e ancora. L’ho riempita di freschezza, giocando con motivi naturalistici e decorazioni sempre nuove. È un processo libero, un’esplorazione che non sa ancora quale forma definitiva prenderà, ma che sento essere il seme di un laboratorio in divenire."),
            ("img", "caraffa-01", "Tante caraffe disegnate con decorazioni blu"),
            ("q", "A volte disegnare significa proprio questo: scavallare il limite dell’oggetto reale per trovare un’idea che ancora non esiste."),
        ],
    },
    {
        "slug": "dal-segno-al-movimento",
        "sezione": "costruire-con-baruch",
        "data": "2026-04-25", "data_it": "25 aprile 2026",
        "titolo": "Dal segno al movimento",
        "sottotitolo": "Un laboratorio di stop motion per bambini",
        "estratto": "Laboratori creativi per bambini: come dare vita a un personaggio attraverso la tecnica dello stop motion.",
        "cover": ("dal-segno-al-movimento-01", "Tanti pupazzetti di carta colorati dai bambini"),
        "blocchi": [
            ("p", "Laboratori creativi per bambini: come dare vita a un personaggio attraverso la tecnica dello stop motion."),
            ("p", "Tutto ha avuto inizio da un dettaglio che ha catturato la mia attenzione: un piccolo omino medievale dipinto su una caraffa di Deruta. Quello che era nato come una sperimentazione personale nel mio diario si è trasformato in una sfida divertente per i più piccoli."),
            ("img", "dal-segno-al-movimento-02", "Il modellino di esempio e i pupazzetti realizzati dai bambini di terza, quarta e quinta elementare"),
            ("img", "dal-segno-al-movimento-03", "Pupazzetti di carta con braccia e gambe snodate in pose di salto"),
        ],
    },
    {
        "slug": "gita-ai-magredi",
        "sezione": "le-avventure-di-baruch",
        "data": "2026-04-10", "data_it": "10 aprile 2026",
        "titolo": "Gita ai Magredi",
        "sottotitolo": "Dove la natura diventa seta",
        "estratto": "I Magredi di San Quirino mi hanno accolta con un’abbondanza di stimoli e di sfumature.",
        "cover": ("gita-ai-magredi-01", "Il prato dei Magredi dipinto con una fila di alberi scuri"),
        "blocchi": [
            ("p", "Ogni luogo mi narra una storia. Oggi, i Magredi di San Quirino mi hanno accolta con un’abbondanza tale di stimoli e sfumature che è stato difficile scegliere quale frammento portare a casa. Non capita anche a voi di sentirvi sopraffatti da tanta bellezza? Questo territorio, così vicino a casa, mi ha regalato uno spettacolo delicato."),
            ("img", "gita-ai-magredi-02", "L’erba alta e argentata dei Magredi"),
            ("img", "gita-ai-magredi-03", "Una persona cammina nella prateria dei Magredi"),
            ("p", "Anche se non ho una preparazione scientifica sulla flora locale, sono rimasta incantata dalla Stipa pennata, nota poeticamente come “Lino delle fate”. Le sue lunghe reste argentate sono così sottili che ondeggiano come fili di seta alla minima brezza. Nella fase di disseminazione, poi, si trasformano in piume impalpabili, pronte a farsi trasportare dal vento come piccoli paracadute magici."),
            ("q", "Già immagino piccole fate intente a raccoglierlo per creare acconciature improbabili…"),
            ("p", "Ho colto al volo qualche foto e alcuni schizzi veloci: materiale prezioso da rielaborare nel mio studio, pensando alla magia che questo “cotone selvatico” suscita in me."),
            ("img", "gita-ai-magredi-04", "Schizzo ad acquerello dei Magredi con la data"),
            ("img", "gita-ai-magredi-05", "Acquerello di un prato chiaro con alberi lontani"),
            ("img", "gita-ai-magredi-06", "Acquerello di una figura nell’erba con appunti a mano"),
            ("img", "gita-ai-magredi-07", "Acquerello del prato verde con alberi scuri"),
        ],
    },
]
